site_name: MFR Driverless Documentation
site_url: https://markadme.github.io/documentation/
nav:
    - General:
        - Guidelines: general/Guidelines.md
        - Framework: general/Framework.md
    - Vehicle navigation:
        - Overview: vehicle-navigation/Overview.md


theme: readthedocs
